// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chunkserver.proto

#include "chunkserver.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace goya {
namespace fs {
class WriteBlockRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WriteBlockRequest>
      _instance;
} _WriteBlockRequest_default_instance_;
class WriteBlockResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WriteBlockResponse>
      _instance;
} _WriteBlockResponse_default_instance_;
}  // namespace fs
}  // namespace goya
namespace protobuf_chunkserver_2eproto {
static void InitDefaultsWriteBlockRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::goya::fs::_WriteBlockRequest_default_instance_;
    new (ptr) ::goya::fs::WriteBlockRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::goya::fs::WriteBlockRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WriteBlockRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWriteBlockRequest}, {}};

static void InitDefaultsWriteBlockResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::goya::fs::_WriteBlockResponse_default_instance_;
    new (ptr) ::goya::fs::WriteBlockResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::goya::fs::WriteBlockResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_WriteBlockResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsWriteBlockResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_WriteBlockRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_WriteBlockResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::ServiceDescriptor* file_level_service_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::goya::fs::WriteBlockRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::goya::fs::WriteBlockRequest, sequence_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::goya::fs::WriteBlockRequest, block_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::goya::fs::WriteBlockResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::goya::fs::WriteBlockResponse, sequence_id_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::goya::fs::WriteBlockRequest)},
  { 7, -1, sizeof(::goya::fs::WriteBlockResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::goya::fs::_WriteBlockRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::goya::fs::_WriteBlockResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "chunkserver.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, file_level_service_descriptors);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021chunkserver.proto\022\007goya.fs\":\n\021WriteBlo"
      "ckRequest\022\023\n\013sequence_id\030\001 \001(\004\022\020\n\010block_"
      "id\030\002 \001(\003\")\n\022WriteBlockResponse\022\023\n\013sequen"
      "ce_id\030\001 \001(\0042T\n\013ChunkServer\022E\n\nWriteBlock"
      "\022\032.goya.fs.WriteBlockRequest\032\033.goya.fs.W"
      "riteBlockResponseB\003\200\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 230);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "chunkserver.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_chunkserver_2eproto
namespace goya {
namespace fs {

// ===================================================================

void WriteBlockRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WriteBlockRequest::kSequenceIdFieldNumber;
const int WriteBlockRequest::kBlockIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WriteBlockRequest::WriteBlockRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chunkserver_2eproto::scc_info_WriteBlockRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:goya.fs.WriteBlockRequest)
}
WriteBlockRequest::WriteBlockRequest(const WriteBlockRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&sequence_id_, &from.sequence_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&block_id_) -
    reinterpret_cast<char*>(&sequence_id_)) + sizeof(block_id_));
  // @@protoc_insertion_point(copy_constructor:goya.fs.WriteBlockRequest)
}

void WriteBlockRequest::SharedCtor() {
  ::memset(&sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&block_id_) -
      reinterpret_cast<char*>(&sequence_id_)) + sizeof(block_id_));
}

WriteBlockRequest::~WriteBlockRequest() {
  // @@protoc_insertion_point(destructor:goya.fs.WriteBlockRequest)
  SharedDtor();
}

void WriteBlockRequest::SharedDtor() {
}

void WriteBlockRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* WriteBlockRequest::descriptor() {
  ::protobuf_chunkserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chunkserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WriteBlockRequest& WriteBlockRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chunkserver_2eproto::scc_info_WriteBlockRequest.base);
  return *internal_default_instance();
}


void WriteBlockRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:goya.fs.WriteBlockRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&sequence_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&block_id_) -
      reinterpret_cast<char*>(&sequence_id_)) + sizeof(block_id_));
  _internal_metadata_.Clear();
}

bool WriteBlockRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:goya.fs.WriteBlockRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 sequence_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &sequence_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 block_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &block_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:goya.fs.WriteBlockRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:goya.fs.WriteBlockRequest)
  return false;
#undef DO_
}

void WriteBlockRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:goya.fs.WriteBlockRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->sequence_id(), output);
  }

  // int64 block_id = 2;
  if (this->block_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->block_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:goya.fs.WriteBlockRequest)
}

::google::protobuf::uint8* WriteBlockRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:goya.fs.WriteBlockRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->sequence_id(), target);
  }

  // int64 block_id = 2;
  if (this->block_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->block_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:goya.fs.WriteBlockRequest)
  return target;
}

size_t WriteBlockRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:goya.fs.WriteBlockRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->sequence_id());
  }

  // int64 block_id = 2;
  if (this->block_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->block_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WriteBlockRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:goya.fs.WriteBlockRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const WriteBlockRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WriteBlockRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:goya.fs.WriteBlockRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:goya.fs.WriteBlockRequest)
    MergeFrom(*source);
  }
}

void WriteBlockRequest::MergeFrom(const WriteBlockRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:goya.fs.WriteBlockRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sequence_id() != 0) {
    set_sequence_id(from.sequence_id());
  }
  if (from.block_id() != 0) {
    set_block_id(from.block_id());
  }
}

void WriteBlockRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:goya.fs.WriteBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WriteBlockRequest::CopyFrom(const WriteBlockRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:goya.fs.WriteBlockRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteBlockRequest::IsInitialized() const {
  return true;
}

void WriteBlockRequest::Swap(WriteBlockRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WriteBlockRequest::InternalSwap(WriteBlockRequest* other) {
  using std::swap;
  swap(sequence_id_, other->sequence_id_);
  swap(block_id_, other->block_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WriteBlockRequest::GetMetadata() const {
  protobuf_chunkserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chunkserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WriteBlockResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WriteBlockResponse::kSequenceIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WriteBlockResponse::WriteBlockResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_chunkserver_2eproto::scc_info_WriteBlockResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:goya.fs.WriteBlockResponse)
}
WriteBlockResponse::WriteBlockResponse(const WriteBlockResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  sequence_id_ = from.sequence_id_;
  // @@protoc_insertion_point(copy_constructor:goya.fs.WriteBlockResponse)
}

void WriteBlockResponse::SharedCtor() {
  sequence_id_ = GOOGLE_ULONGLONG(0);
}

WriteBlockResponse::~WriteBlockResponse() {
  // @@protoc_insertion_point(destructor:goya.fs.WriteBlockResponse)
  SharedDtor();
}

void WriteBlockResponse::SharedDtor() {
}

void WriteBlockResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* WriteBlockResponse::descriptor() {
  ::protobuf_chunkserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chunkserver_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WriteBlockResponse& WriteBlockResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_chunkserver_2eproto::scc_info_WriteBlockResponse.base);
  return *internal_default_instance();
}


void WriteBlockResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:goya.fs.WriteBlockResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sequence_id_ = GOOGLE_ULONGLONG(0);
  _internal_metadata_.Clear();
}

bool WriteBlockResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:goya.fs.WriteBlockResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 sequence_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &sequence_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:goya.fs.WriteBlockResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:goya.fs.WriteBlockResponse)
  return false;
#undef DO_
}

void WriteBlockResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:goya.fs.WriteBlockResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->sequence_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:goya.fs.WriteBlockResponse)
}

::google::protobuf::uint8* WriteBlockResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:goya.fs.WriteBlockResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->sequence_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:goya.fs.WriteBlockResponse)
  return target;
}

size_t WriteBlockResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:goya.fs.WriteBlockResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint64 sequence_id = 1;
  if (this->sequence_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->sequence_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void WriteBlockResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:goya.fs.WriteBlockResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const WriteBlockResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WriteBlockResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:goya.fs.WriteBlockResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:goya.fs.WriteBlockResponse)
    MergeFrom(*source);
  }
}

void WriteBlockResponse::MergeFrom(const WriteBlockResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:goya.fs.WriteBlockResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sequence_id() != 0) {
    set_sequence_id(from.sequence_id());
  }
}

void WriteBlockResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:goya.fs.WriteBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WriteBlockResponse::CopyFrom(const WriteBlockResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:goya.fs.WriteBlockResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WriteBlockResponse::IsInitialized() const {
  return true;
}

void WriteBlockResponse::Swap(WriteBlockResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WriteBlockResponse::InternalSwap(WriteBlockResponse* other) {
  using std::swap;
  swap(sequence_id_, other->sequence_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata WriteBlockResponse::GetMetadata() const {
  protobuf_chunkserver_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_chunkserver_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

ChunkServer::~ChunkServer() {}

const ::google::protobuf::ServiceDescriptor* ChunkServer::descriptor() {
  protobuf_chunkserver_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_chunkserver_2eproto::file_level_service_descriptors[0];
}

const ::google::protobuf::ServiceDescriptor* ChunkServer::GetDescriptor() {
  return descriptor();
}

void ChunkServer::WriteBlock(::google::protobuf::RpcController* controller,
                         const ::goya::fs::WriteBlockRequest*,
                         ::goya::fs::WriteBlockResponse*,
                         ::google::protobuf::Closure* done) {
  controller->SetFailed("Method WriteBlock() not implemented.");
  done->Run();
}

void ChunkServer::CallMethod(const ::google::protobuf::MethodDescriptor* method,
                             ::google::protobuf::RpcController* controller,
                             const ::google::protobuf::Message* request,
                             ::google::protobuf::Message* response,
                             ::google::protobuf::Closure* done) {
  GOOGLE_DCHECK_EQ(method->service(), protobuf_chunkserver_2eproto::file_level_service_descriptors[0]);
  switch(method->index()) {
    case 0:
      WriteBlock(controller,
             ::google::protobuf::down_cast<const ::goya::fs::WriteBlockRequest*>(request),
             ::google::protobuf::down_cast< ::goya::fs::WriteBlockResponse*>(response),
             done);
      break;
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      break;
  }
}

const ::google::protobuf::Message& ChunkServer::GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::goya::fs::WriteBlockRequest::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->input_type());
  }
}

const ::google::protobuf::Message& ChunkServer::GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const {
  GOOGLE_DCHECK_EQ(method->service(), descriptor());
  switch(method->index()) {
    case 0:
      return ::goya::fs::WriteBlockResponse::default_instance();
    default:
      GOOGLE_LOG(FATAL) << "Bad method index; this should never happen.";
      return *::google::protobuf::MessageFactory::generated_factory()
          ->GetPrototype(method->output_type());
  }
}

ChunkServer_Stub::ChunkServer_Stub(::google::protobuf::RpcChannel* channel)
  : channel_(channel), owns_channel_(false) {}
ChunkServer_Stub::ChunkServer_Stub(
    ::google::protobuf::RpcChannel* channel,
    ::google::protobuf::Service::ChannelOwnership ownership)
  : channel_(channel),
    owns_channel_(ownership == ::google::protobuf::Service::STUB_OWNS_CHANNEL) {}
ChunkServer_Stub::~ChunkServer_Stub() {
  if (owns_channel_) delete channel_;
}

void ChunkServer_Stub::WriteBlock(::google::protobuf::RpcController* controller,
                              const ::goya::fs::WriteBlockRequest* request,
                              ::goya::fs::WriteBlockResponse* response,
                              ::google::protobuf::Closure* done) {
  channel_->CallMethod(descriptor()->method(0),
                       controller, request, response, done);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace fs
}  // namespace goya
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::goya::fs::WriteBlockRequest* Arena::CreateMaybeMessage< ::goya::fs::WriteBlockRequest >(Arena* arena) {
  return Arena::CreateInternal< ::goya::fs::WriteBlockRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::goya::fs::WriteBlockResponse* Arena::CreateMaybeMessage< ::goya::fs::WriteBlockResponse >(Arena* arena) {
  return Arena::CreateInternal< ::goya::fs::WriteBlockResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
